# In-Class Programming Activity, Day 6
### Melissa Leong 
### Date: 17/02/2017

####Task 1
```{r}
make_one_bar<-function(point){
  xLeft<-point$xL
  xRight<-point$xR
  height<-point$count
  res<-data.frame(
    x=c(xLeft,xLeft,xRight,xRight,NA),
    y=c(0,height,height,0,NA)
  )
  res
}

one_to_five<-function(hist_data) {
  bars<-NULL
  for(k in 1:nrow(hist_data)){
    new_bar<-make_one_bar(hist_data[k,])
    bars<-rbind(bars,new_bar)
  }
  bars
}

myHistogram<-function(data){
  histData<-data.frame(one_to_five(data))
  plot(histData,type="n")
  lines(histData)
  polygon(histData,col="salmon")
  xfit<-seq(min(histData$x,na.rm=TRUE),max(histData$x,na.rm=TRUE),length=100)
  m<-mean(x,na.rm=TRUE)
  std<-sqrt(var(x,na.rm=TRUE))
  yfit<-dnorm(xfit,m,std)
  lines(yfit,col="red")
}
myHistogram()
```

####Task 2
```{r}


#Note: large bandwidths produce very smooth estimates, small values produce wiggly estimates
kernel<-function(values) {#This function called "kernel" takes specified values "values" and 
  bw<-range(values)/sqrt(length(values))
  density(values,bw)
} 

v<-rnorm(10,mean=100,sd=1)
bw<-range(v)/sqrt(10)
x<-rnorm(10,mean=100,sd=1) #I increase the sd here to 1.2 to allow values that extend several bandwiths that extend to either side of the range of v 
kernel(v)


Dvals <- outer(v,x,FUN=kernel)
Dvals

```

####Task 3
```{r}

```

####Task 4
```{r}

```

####Task 5
```{r}

```

## Test statements

```{r}
scoreActivity::score253(6)
```