# In-Class Programming Activity, Day 7

```{r}
library(graphics)
library(devtools)
```

```{r}
#1) 
vals<- rexp(10,(1/100)) #creates 10 values that have a prob of occuring at a rate of 1/100 within the exponential distribution

#2) 
#Create an object test200 that gives the log-likelihood of vals for a rate of 1/200. You can use dexp() for this, along with sum() and log(). The dexp() function will calculate the likelihood of each of the 10 values independently in vals. Ordinarily, you would multiply them together to find the likelihood of the 10 values taken as a set. For log-likelihood, take the log of the output of dexp() — producing a 10 number result. Then sum over those numbers to get the log-likelihood.
test200<-sum(log(dexp(vals,rate=1/200)))

#3)
#Write a function LL_exp(rate) that computes the log-likelihood of vals for the given rate. Test it out by comparing the result to what you got in (2).
LL_exp<-function(aRate) {
  vals<-rexp(10,(aRate))
  testRate<-dexp(vals,rate=1/200)
  testRate<- log(testRate)
  testRate<-sum(testRate)
}

print(LL_exp(1/200))

#4) Create an object rates that is a vector of many rates between 1/50 and 1/200.
rates<- runif(n=100,min=0.005,max=0.02) #generates 1000 observations of such rates

#5) You are going to compute the log-likelihood of vals for each component of rates.
results <- sapply(rates, LL_exp)
results

#6)
plot(results,rates)


#7)
#Create an object exp_results that contains the output of optimize(). Check it to make sure that your answer is consistent with that in Task 1.
exp_results<- optimize(LL_exp,lower=1/200,upper=1/50,maximum=TRUE)
```


## Test statements

```{r}
scoreActivity::score253(7)
```